apiVersion: v1
kind: Service
metadata:
  name: dityudha-afi-services
spec:
  type: NodePort
  selector:
    app: dityudha-afi-v3
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30008
